version: '3'

services:
    postgres:
        image: postgres:12
        restart: always
        ports:
            - '5432:5432'    
        volumes:
            - ./db_data:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
        env_file:
            - ./config/.env
        networks:
            - backend    
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "devdb", "-U","postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
    redis:
        image: redis:6.2
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - backend      
        ports:
          - 6379:6379 
    app:
        build: ./
        ports:
          - 8000:8000
        depends_on:
          - postgres
        networks:
          - backend

networks:
  backend:
    driver: bridge