postgresql:
  username: postgres
  password: Loken
  host: postgres
  port: 5432
  dbname: devdb
  poolsize: 100

redis:
  host: redis
  port: 6379
  password: ""
  dbnumber: 0

port: 8080
host: localhost
loglvl : debug

